blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://community.quicksales.vn
    about: Suggest an idea for this project
  - name: Question / Problem
    url: https://community.quicksales.vn
    about: Questions and problems with n8n
